### ISSUE TITLE
eslint-config import error

### ISSUE THREAD

**Issue by blasdfaa** [artalar/reatom#857]
### What happened?

When using the `@reatom/eslint-config` package with eslint flat config, an unexpected syntax error occurs during the fix process. The error message is as follows:
```bash
SyntaxError: Unexpected token 'export'
```
It seems that the error is related to the use of the export keyword, which is unexpected in this context

### Steps to reproduce:

1. Go to https://stackblitz.com/edit/vitejs-vite-cvi2tb?file=eslint.config.js
2. Uncomment line 6
3. Run `npx eslint --fix`

### Part

Package @reatom/eslint-plugin

### Version

3.4.3

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
SyntaxError: Unexpected token 'export'
    at internalCompileFunction (https://vitejsvitecvi2tb-hqal.w-credentialless-staticblitz.com/builtins.5bf3667c.js:266:849)
    at wrapSafe (https://vitejsvitecvi2tb-hqal.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:13497)
    at Module._compile (https://vitejsvitecvi2tb-hqal.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:13881)
    at Module._extensions..js (https://vitejsvitecvi2tb-hqal.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:14855)
    at Module.load (https://vitejsvitecvi2tb-hqal.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:12820)
    at Module._load (https://vitejsvitecvi2tb-hqal.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:10273)
```

**Comment by artalar** [comment]
I will try to find someone to address this within a week.

**Comment by artalar** [comment]
Fixed in `@reatom/elint-plugin@experimental`
